# Generated by Django 6.0.1 on 2026-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
