# Generated by Django 6.0.1 on 2026-01-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Confirm_password',
        ),
    ]
