# Generated by Django 6.0.1 on 2026-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_data_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Contact',
            field=models.CharField(max_length=15),
        ),
    ]
