# Generated by Django 6.0.1 on 2026-02-11 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xyz', to='app.aadhar'),
        ),
    ]
