# Generated by Django 6.0.1 on 2026-02-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Query', models.TextField()),
                ('Department', models.CharField(max_length=50)),
                ('Status', models.CharField(blank=True, max_length=50)),
                ('Admin_replay', models.CharField(default='pending', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
