# Generated by Django 6.0.1 on 2026-02-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_query_alter_password_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Admin_replay',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='query',
            name='Status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
